=== ColeTrammer/iros/gen/port_manager/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "properties": {
        "name": {
            "type": "string"
        },
        "version": {
            "type": "string"
        },
        "download": {
            "oneOf": [
                {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string",
                            "enum": [
                                "git"
                            ]
                        },
                        "url": {
                            "type": "string",
                            "format": "uri"
                        }
                    },
                    "required": [
                        "type",
                        "url"
                    ]
                },
                {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string",
                            "enum": [
                                "tarball"
                            ]
                        },
                        "kind": {
                            "type": "string",
                            "enum": [
                                "gz",
                                "xz"
                            ]
                        },
                        "url": {
                            "type": "string",
                            "format": "uri"
                        },
                        "signature": {
                            "type": "string",
                            "format": "uri"
                        }
                    },
                    "required": [
                        "type",
                        "kind",
                        "url"
                    ]
                }
            ]
        },
        "patch": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "pattern": "^.+\\.patch$"
                    }
                }
            },
            "required": [
                "files"
            ]
        },
        "buildSystem": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "autoconf",
                        "basic",
                        "cmake"
                    ]
                },
                "configure": {
                    "env": {
                        "$ref": "#/definitions/key_value_pairs"
                    },
                    "settings": {
                        "$ref": "#/definitions/key_value_pairs"
                    }
                },
                "build": {},
                "install": {}
            },
            "required": [
                "type"
            ]
        },
        "dependencies": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "definitions": {
        "key_value_pairs": {
            "type": "object",
            "patternProperties": {
                ".+": {
                    "type": "string"
                }
            }
        }
    }
}

=== ColeTrammer/iros/legacy/ports/ncurses/port.json
{
    "name": "ncurses",
    "version": "6.2",
    "download": {
        "type": "tarball",
        "url": "ftp://ftp.invisible-island.net/ncurses/ncurses-6.2.tar.gz",
        "kind": "gz",
        "signature": "ftp://ftp.invisible-island.net/ncurses/ncurses-6.2.tar.gz.asc",
        "sourceDirectory": "ncurses-6.2"
    },
    "patch": {
        "files": [
            "ncurses-6.2.patch"
        ]
    },
    "buildSystem": {
        "type": "autoconf",
        "configure": {
            "settings": {
                "--with-termlib": true,
                "--with-shared": true
            }
        },
        "build": {},
        "install": {}
    }
}

=== ColeTrammer/iros/ports/ninja/port.json
{
    "name": "ninja",
    "version": "latest",
    "download": {
        "type": "git",
        "url": "https://github.com/ninja-build/ninja.git"
    },
    "patch": {
        "files": [
            "ninja.patch"
        ]
    },
    "buildSystem": {
        "type": "cmake",
        "configure": {},
        "build": {},
        "install": {}
    }
}

=== ColeTrammer/iros/ports/bash/port.json
{
    "name": "bash",
    "version": "5.0",
    "download": {
        "type": "tarball",
        "kind": "gz",
        "url": "https://ftp.gnu.org/gnu/bash/bash-5.0.tar.gz",
        "signature": "https://ftp.gnu.org/gnu/bash/bash-5.0.tar.gz.sig",
        "sourceDirectory": "bash-5.0"
    },
    "patch": {
        "files": [
            "bash-5.0-loadables.patch",
            "bash-5.0.patch"
        ]
    },
    "buildSystem": {
        "type": "autoconf",
        "configure": {
            "env": {
                "bash_cv_getcwd_malloc": "yes"
            },
            "settings": {
                "--disable-nls": true,
                "--without-bash-malloc": true
            }
        },
        "build": {},
        "install": {}
    },
    "dependencies": [
        "ncurses"
    ]
}

=== ColeTrammer/iros/ports/curl/port.json
{
    "name": "curl",
    "version": "7.71.1",
    "download": {
        "type": "tarball",
        "url": "https://curl.se/download/curl-7.71.1.tar.gz",
        "kind": "gz",
        "signature": "https://curl.se/download/curl-7.71.1.tar.gz.asc",
        "sourceDirectory": "curl-7.71.1"
    },
    "patch": {
        "files": [
            "curl-7.71.1.patch"
        ]
    },
    "buildSystem": {
        "type": "autoconf",
        "configure": {
            "env": {
                "curl_disallow_getaddrinfo": "yes"
            },
            "settings": {
                "--with-shared": true,
                "--disable-ipv6": true
            }
        },
        "build": {},
        "install": {}
    }
}
